# Random Forest

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score
from sklearn.model_selection import GridSearchCV, train_test_split
import pickle

### Definir get_metrics

In [2]:
def get_classifier_metrics(y_predict_test, y_test, y_predict_train, y_train, average='micro'):
    metrics_train = (accuracy_score(y_train, y_predict_train),
                     f1_score(y_train, y_predict_train, average=average),
                     precision_score(y_train, y_predict_train, average=average),
                     recall_score(y_train, y_predict_train, average=average))
    metrics_test = (accuracy_score(y_test, y_predict_test),
                    f1_score(y_test, y_predict_test, average=average),
                    precision_score(y_test, y_predict_test, average=average),
                    recall_score(y_test, y_predict_test, average=average))
    return pd.DataFrame(data=[metrics_train, metrics_test],
                        columns=['Accuracy', 'F1 Score', 'Precision', 'Recall'],
                        index=['Train set', 'Test set'])

### Recopliacion de datos

In [3]:
df= pd.read_csv("../data/processed/diabetes_imputado.csv")
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6.0,148.0,72.0,35.0,0.0,33.6,0.6270,50.0,1.0
1,1.0,85.0,66.0,29.0,0.0,26.6,0.3510,31.0,0.0
2,8.0,183.0,64.0,0.0,0.0,23.3,0.6720,32.0,1.0
3,1.0,89.0,66.0,23.0,94.0,28.1,0.1670,21.0,0.0
4,0.0,137.0,40.0,35.0,168.0,43.1,0.7048,33.0,1.0

#### Split

In [4]:
X = df.drop("Outcome", axis=1)
y = df["Outcome"]

X_train, X_test, y_train, y_test = train_test_split(X, y, 
                                                    test_size=0.2, 
                                                    random_state=42)

### Modelado

In [5]:
model= RandomForestClassifier(random_state=42)
model.fit(X_train, y_train)
y_predict_train = model.predict(X_train)
y_predict_test = model.predict(X_test)
metrics = get_classifier_metrics(y_predict_test, y_test, y_predict_train, y_train)
metrics

           Accuracy  F1 Score  Precision    Recall
Train set  1.000000  1.000000   1.000000  1.000000
Test set   0.772727  0.772727   0.772727  0.772727

### Optimización del modelo

In [6]:
hiperparameters = {
    'n_estimators': [10, 50, 100],
    'max_depth': [None, 10, 20],
    'bootstrap': [True, False],
    'criterion': ['gini', 'entropy', 'log_loss'],
    'max_features': ['auto', 'sqrt', 'log2'],
    'class_weight': [None, 'balanced']
}
grid_search = GridSearchCV(estimator=model,
                           param_grid=hiperparameters,
                           scoring='accuracy',
                           cv=5,
                           verbose=1,
                            n_jobs=-1)
grid_search.fit(X_train, y_train)
best_model = grid_search.best_estimator_
y_predict_train_best = best_model.predict(X_train)
y_predict_test_best = best_model.predict(X_test)
metrics_best = get_classifier_metrics(y_predict_test_best, y_test, y_predict_train_best, y_train)
metrics_best

Fitting 5 folds for each of 324 candidates, totalling 1620 fits

/home/vscode/.local/lib/python3.11/site-packages/sklearn/model_selection/_validation.py:516: FitFailedWarning:
540 fits failed out of a total of 1620.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
540 fits failed with the following error:
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.11/site-packages/sklearn/model_selection/_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/vscode/.local/lib/python3.11/site-packages/sklearn/base.py", line 1356, in wrapper
    estimator._validate_params()
  File "/home/vscode/.local/lib/python3.11/site-packages/sklearn/base.py", line 469, in _validate_params
    validate_parameter_constraints(
  File "/home/vscode/.local/lib/python3.11/site-packages/sklearn/utils/_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'sqrt', 'log2'} or None. Got 'auto' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
/home/vscode/.local/lib/python3.11/site-packages/sklearn/model_selection/_search.py:1135: UserWarning: One or more of the test scores are non-finite: [       nan        nan        nan 0.74423564 0.78348661 0.78345995
 0.74755431 0.77038518 0.77035852        nan        nan        nan
 0.75568439 0.77692923 0.77042516 0.73773157 0.77035852 0.77037185
        nan        nan        nan 0.74098361 0.78511262 0.78345995
 0.74755431 0.77038518 0.77035852        nan        nan        nan
 0.75245902 0.77361056 0.77038518 0.75569772 0.76220179 0.77037185
        nan        nan        nan 0.7524057  0.76385446 0.77362388
 0.74263628 0.77033187 0.78336665        nan        nan        nan
 0.75245902 0.77523657 0.77038518 0.75569772 0.76220179 0.77037185
        nan        nan        nan 0.75245902 0.77361056 0.77038518
 0.75569772 0.76220179 0.77037185        nan        nan        nan
 0.7524057  0.76385446 0.77362388 0.74263628 0.77033187 0.78336665
        nan        nan        nan 0.75245902 0.77523657 0.77038518
 0.75569772 0.76220179 0.77037185        nan        nan        nan
 0.75244569 0.76871918 0.76384113 0.75245902 0.75401839 0.76381447
        nan        nan        nan 0.76224177 0.76546715 0.76877249
 0.75731041 0.76386779 0.7638278         nan        nan        nan
 0.75244569 0.76871918 0.76384113 0.75245902 0.75401839 0.76381447
        nan        nan        nan 0.74756764 0.76056244 0.75569772
 0.73942423 0.76384113 0.76056244        nan        nan        nan
 0.75569772 0.75893643 0.76385446 0.74590164 0.77523657 0.77197121
        nan        nan        nan 0.74756764 0.76057577 0.75733707
 0.73942423 0.76384113 0.75893643        nan        nan        nan
 0.74756764 0.76056244 0.75569772 0.73942423 0.76384113 0.76056244
        nan        nan        nan 0.75569772 0.75893643 0.76385446
 0.74590164 0.77523657 0.77197121        nan        nan        nan
 0.74756764 0.76057577 0.75733707 0.73942423 0.76384113 0.75893643
        nan        nan        nan 0.74752766 0.76544049 0.7735839
 0.73938425 0.76060243 0.76542716        nan        nan        nan
 0.74760762 0.76874583 0.76714647 0.74262295 0.76871918 0.76218846
        nan        nan        nan 0.74752766 0.76544049 0.77684926
 0.73938425 0.76060243 0.76542716        nan        nan        nan
 0.74427562 0.76871918 0.77851526 0.73614554 0.7638278  0.7589231
        nan        nan        nan 0.7638278  0.75896308 0.77361056
 0.73451953 0.76710649 0.76871918        nan        nan        nan
 0.74590164 0.76546715 0.77851526 0.73451953 0.76545382 0.76054911
        nan        nan        nan 0.74427562 0.76871918 0.77851526
 0.73614554 0.7638278  0.7589231         nan        nan        nan
 0.7638278  0.75896308 0.77361056 0.73451953 0.76710649 0.76871918
        nan        nan        nan 0.74590164 0.76546715 0.77851526
 0.73451953 0.76545382 0.76054911        nan        nan        nan
 0.75248567 0.77365054 0.77362388 0.74756764 0.76217513 0.76054911
        nan        nan        nan 0.73949087 0.76546715 0.7703452
 0.75241903 0.76218846 0.76053579        nan        nan        nan
 0.75248567 0.77365054 0.77199787 0.74756764 0.76217513 0.76054911
        nan        nan        nan 0.7442623  0.74754098 0.76545382
 0.72473677 0.76053579 0.76056244        nan        nan        nan
 0.7459283  0.76385446 0.77365054 0.74106357 0.75729708 0.76381447
        nan        nan        nan 0.74427562 0.74102359 0.76217513
 0.72636279 0.75890977 0.76218846        nan        nan        nan
 0.7442623  0.74754098 0.76545382 0.72473677 0.76053579 0.76056244
        nan        nan        nan 0.7459283  0.76385446 0.77365054
 0.74106357 0.75729708 0.76381447        nan        nan        nan
 0.74427562 0.74102359 0.76217513 0.72636279 0.75890977 0.76218846]
  warnings.warn(

           Accuracy  F1 Score  Precision   Recall
Train set   1.00000   1.00000    1.00000  1.00000
Test set    0.74026   0.74026    0.74026  0.74026

### Guardado del modelo

In [7]:
with open('/workspaces/infoasir20-primer-algoritmo/models/random-forest-model.pkl', 'wb') as file:
    pickle.dump(model, file)