# SPAM

### Importamos las librerias

In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import regex as re
from nltk import download
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from wordcloud import WordCloud
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.svm import SVC
import warnings

“Ignora todos los warnings y no los muestres en pantalla”.

In [10]:
warnings.filterwarnings("ignore")

### Leemos el Dataset

In [11]:
df= pd.read_csv("../data/raw/url_spam.csv")
df

                                                    url  is_spam
0     https://briefingday.us8.list-manage.com/unsubs...     True
1                                https://www.hvper.com/     True
2                    https://briefingday.com/m/v4n3i4f3     True
3      https://briefingday.com/n/20200618/m#commentform    False
4                           https://briefingday.com/fan     True
...                                                 ...      ...
2994  https://www.smartcitiesworld.net/news/news/dee...    False
2995                      https://www.youtube.com/watch     True
2996  https://techcrunch.com/2019/07/04/an-optimisti...    False
2997  https://www.technologyreview.com/2019/12/20/13...    False
2998       https://www.bbc.com/news/technology-51018758    False

[2999 rows x 2 columns]

In [12]:
df.describe()

                                         url is_spam
count                                   2999    2999
unique                                  2369       2
top     https://www.bloomberg.com/tosv2.html   False
freq                                      26    2303

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2999 entries, 0 to 2998
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   url      2999 non-null   object
 1   is_spam  2999 non-null   bool
dtypes: bool(1), object(1)
memory usage: 26.5+ KB

### Procesamos los datos.